In [1]:
import numpy as np

In [5]:
cars=[1,2,3,4,5]
cars


[1, 2, 3, 4, 5]

In [4]:
cars2=np.array([1,2,3,4,5])
cars2

array([1, 2, 3, 4, 5])

In [6]:
average=cars2.mean()
average

np.float64(3.0)

In [7]:
print(np.min(cars2))

1


In [ ]:
#creating a zero array
zero_array=np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones_array=np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

sum_array=arr1+arr2
sum_array

array([5, 7, 9])

In [ ]:
print(np.shape(arr1))
print(np.shape(ones_array))

(3,)
(2, 3)


In [13]:
data=np.array([1,2,3,4,5,6,7,8,9])

print(data[3])

4


In [54]:
#generate random np array
random_array=np.random.rand(3,4)

print(random_array)
print(random_array.shape)

z=np.floor(random_array*10)
print(z)



[[0.54060356 0.25968514 0.64028038 0.54127373]
 [0.80283205 0.55836363 0.33089434 0.56237773]
 [0.44717745 0.18858568 0.32103787 0.9699649 ]]
(3, 4)
[[5. 2. 6. 5.]
 [8. 5. 3. 5.]
 [4. 1. 3. 9.]]


In [55]:
print(z.transpose())

[[5. 8. 4.]
 [2. 5. 1.]
 [6. 3. 3.]
 [5. 5. 9.]]
